// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Takwene.Infrastructure.Persistence;

#nullable disable

namespace Takwene.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Takwene.Domain.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Saudi Arabia",
                            Email = "layla@example.com",
                            Name = "Layla Hassan"
                        },
                        new
                        {
                            Id = 2,
                            Country = "United States",
                            Email = "marcus@example.com",
                            Name = "Marcus Lee"
                        },
                        new
                        {
                            Id = 3,
                            Country = "United Kingdom",
                            Email = "nadia@example.com",
                            Name = "Nadia Petrova"
                        });
                });

            modelBuilder.Entity("Takwene.Domain.Models.Dsp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Dsps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spotify"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Apple Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "YouTube"
                        });
                });

            modelBuilder.Entity("Takwene.Domain.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Isrc")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Isrc")
                        .IsUnique();

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Genre = "Pop",
                            Isrc = "SAA112500001",
                            ReleaseDate = new DateOnly(2025, 2, 1),
                            Status = "Distributed",
                            Title = "Desert Dawn"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            Genre = "Hip-Hop",
                            Isrc = "USRC17600002",
                            ReleaseDate = new DateOnly(2024, 11, 20),
                            Status = "Submitted",
                            Title = "Night Drive"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            Genre = "Electronic",
                            Isrc = "GBA112500003",
                            ReleaseDate = new DateOnly(2025, 1, 10),
                            Status = "Distributed",
                            Title = "Echoes"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 1,
                            Genre = "R&B",
                            Isrc = "SAA112500004",
                            ReleaseDate = new DateOnly(2025, 3, 5),
                            Status = "Draft",
                            Title = "Golden Hour"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 2,
                            Genre = "Rock",
                            Isrc = "USRC17600005",
                            ReleaseDate = new DateOnly(2024, 9, 15),
                            Status = "Distributed",
                            Title = "City Lights"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 1,
                            Genre = "Electronic",
                            Isrc = "SAA112500006",
                            ReleaseDate = new DateOnly(2025, 2, 18),
                            Status = "Submitted",
                            Title = "Mirage"
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 2,
                            Genre = "Pop",
                            Isrc = "USRC17600007",
                            ReleaseDate = new DateOnly(2025, 4, 1),
                            Status = "Draft",
                            Title = "Reckless"
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 3,
                            Genre = "Indie",
                            Isrc = "GBA112500008",
                            ReleaseDate = new DateOnly(2024, 12, 25),
                            Status = "Distributed",
                            Title = "Aurora"
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 1,
                            Genre = "Afrobeat",
                            Isrc = "SAA112500009",
                            ReleaseDate = new DateOnly(2025, 3, 22),
                            Status = "Submitted",
                            Title = "Sandstorm"
                        });
                });

            modelBuilder.Entity("Takwene.Domain.Models.TrackDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DspId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DspId");

                    b.HasIndex("TrackId", "DspId")
                        .IsUnique();

                    b.ToTable("TrackDistributions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DspId = 1,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 1
                        },
                        new
                        {
                            Id = 2,
                            DspId = 2,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 1
                        },
                        new
                        {
                            Id = 3,
                            DspId = 3,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 1
                        },
                        new
                        {
                            Id = 4,
                            DspId = 1,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 3
                        },
                        new
                        {
                            Id = 5,
                            DspId = 3,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 3
                        },
                        new
                        {
                            Id = 6,
                            DspId = 1,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 5
                        },
                        new
                        {
                            Id = 7,
                            DspId = 2,
                            Status = "Rejected",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 5
                        },
                        new
                        {
                            Id = 8,
                            DspId = 2,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 8
                        },
                        new
                        {
                            Id = 9,
                            DspId = 1,
                            Status = "Pending",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 2
                        },
                        new
                        {
                            Id = 10,
                            DspId = 3,
                            Status = "Pending",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 6
                        },
                        new
                        {
                            Id = 11,
                            DspId = 1,
                            Status = "Pending",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 9
                        },
                        new
                        {
                            Id = 12,
                            DspId = 2,
                            Status = "Pending",
                            SubmittedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = 9
                        });
                });

            modelBuilder.Entity("Takwene.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Takwene.Domain.Models.Track", b =>
                {
                    b.HasOne("Takwene.Domain.Models.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Takwene.Domain.Models.TrackDistribution", b =>
                {
                    b.HasOne("Takwene.Domain.Models.Dsp", "Dsp")
                        .WithMany("Distributions")
                        .HasForeignKey("DspId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Takwene.Domain.Models.Track", "Track")
                        .WithMany("Distributions")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dsp");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Takwene.Domain.Models.Artist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Takwene.Domain.Models.Dsp", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("Takwene.Domain.Models.Track", b =>
                {
                    b.Navigation("Distributions");
                });
#pragma warning restore 612, 618
        }
    }
}
